# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e4f2a01a0581e8ada4f7d3fcc633d41ff63d9f97333ffed654e8edb984fd0a0cc280a6a65038f9c2fd596d249c0fe229544a24d1fd0383aa44b486bee1a966

test:
  secret_key_base: 71835d5358fed814c502715e70bb75d79c7f5250506230a2a7188a821dbd88fefaba6dc507bd77ef287137ad04e17665618ff7ef4f3b27bcefbe5fb7dfceb87c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
